# Generated by Django 3.2.6 on 2021-08-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-id',)},
        ),
    ]
